<?php
return [
    'company' => 'company',
    'about us' => 'about us',
    'our team' => 'our team',
    'projects' => 'projects',
    'news' => 'news',
    'sectors title' => 'sectors',
    'marine works' => 'marine works',
    'building materials' => 'building materials',
    'civil and industrial projects' => 'civil and industrial projects',
    'contacts' => 'contacts',
    'language' => 'lan',
    'language1' => 'geo',
    'language2' => 'ru',
    'font-family' => ['_eng_ru_c', '_eng_ru_n'],
    'gd2023' => 'Georgian Development LLC 2023',
    'important projects' => 'important projects',
    'about company' => 'About company',
    'fully' => 'read more',
    'about company text' => 'Our mission and inspiration is to build European infrastructure. European infrastructure does not mean only a high-quality bridge or a beautiful sidewalk. It is also about the European ecosystem – an environment that fosters innovation, growth and creativity for employees, suppliers, customers and citizens. Only in such an environment, and only by caring for each other and the outside world, can we achieve sustainable infrastructure development...',
    'grid titles' => ["Construction of wastewater treatment plant", "„Pace Terminal“ project in Poti", "Construction of civil facilities."],
    'grid dates' => ["December 3, 2017", "September 13, 2015", "June 23, 2019"],
    'grid text' => ["On September 4, 2023, of the National Bank of GeorgiaFollowing the approval of the final prospectus by Prime Concrete Ltd. (the Company) has commenced a $7,500,000...", "After Urek, Anaklia and Gardban, this is Prime Concrete's fourth successfully completed project!", "Prime concrete continues to Construction of a new deepwater berth at the PACE terminal in Poti. New..."],
    'carousel titles' => ["Container Terminal", "Rehabilitation of Berth 7, Poti", "Poti Apartment", "Berth-7", "Berth-15"],
    'carousel text' => ["Customer: Smart DevelopmentContractor: Prime ConcreteContract type: design and constructionCost: 1.5 million USD Foti Apartment...", "Construction of reinforced concrete industrial roads and squares and municipal concrete paved roads is one of our...", "Georgian construction company Prime Concrete starts the new Pace Terminal project in Poti, co-financed by the USA...", "Lego blocks - a simple but versatile, effective and economical choice. The blocks fit together and...", "The foundation slab of the first floor of the school building was poured . A school built with the highest construction standards, in 2021..."],
    'fb' => 'facebook',
    'mail' => 'mail',
    'map' => 'Find us on the map',
    'small menu contacts' => ["home", "contacts"],
    'small menu news' => ["home", "news"],
    'small menu projectsPg' => ["home", "projects"],
    'small menu about' => ["home", "about"],
    'small menu team' => ["home", "team"],
    'small menu berth-7' => ["home", "projects", "berth-7"],
    'small menu berth-15' => ["home", "projects", "ნავმისადგომი-15"],
    'small menu container-terminal' => ["home", "projects", "container terminal"],
    'small menu lego-blocks' => ["home", "projects", "Rehabilitation of the 7th berth, Poti"],
    'small menu pay-terminal' => ["home", "projects", "pay terminal"],
    'small menu poti-apartment' => ["home", "projects", "poti apartment"],
    'small menu building-materials' => ["home", "building-materials"],
    'small menu civil-industrial-projects' => ["home", "civil and industrial projects"],
    'small menu marine-works' => ["home", "marine works"],
    'rights' => "2024 'Georgian Development 2023 LLC'. all rights reserved",
    'about us texts' => [
        "Our Mission And Inspiration Is The Creation Of European Infrastructure. European Infrastructure Is Not Only About A High-Quality Bridge Or A Beautiful Sidewalk. It Is Also About The European Ecosystem – An Environment That Fosters Innovation, Growth And Creativity Among Employees, Suppliers, Customers And Citizens. Only In Such An Environment And Only By Taking Care Of Each Other And The Outside World Can We Achieve Sustainable Infrastructure Development. Our Qualified Engineers, Construction Specialists And Project Managers Work With Customers, Partners And Our Extensive Supply Chain To Develop Innovative Technical Solutions. Design And Commercial Solutions For Projects Of Any Size And Complexity, Including But Not Limited To:",
        ["Infrastructure Of Ports And Terminals", "Roads", "Water Treatment Infrastructure", "Industrial And Public Buildings"],
        "Prime Concrete's Building Materials Department Produces A Wide Range Of High-Quality Building Materials And Products, Including:",
        ["Concrete And Inert Materials", "Concrete Blocks And Paving Stones", "Ready-Made Concrete Elements"],
        "Prime Concrete's Approaches Are Client-Oriented. The Company Believes In Providing Its Customers With Flexible And Optimal Services That Are In Line With Price And Quality. To Serve Key Markets, We Have Developed Our Internal Capabilities, Which Have Given Us The Means To Improve Operational Efficiency, Develop Our Skills And Manage Our Own Projects. As A Result Of All This, We Have Increased Our Ability To Perform Excavation, Concrete, Drainage, Mechanical And Electrical Work. All Components Of Prime Concrete Share The Same Security Systems, Culture And Approaches. Therefore, We Have A Reduced Vertical Hierarchy, Therefore Fewer Cases, Which Often Become A Source Of Contractual Disputes, Risks And Shortcomings In Communications. By Directly Managing Projects, Prime Beton Takes Full Responsibility For Responding To Customer Needs."
    ],
    'team texts' => [
        "'Prime Concrete' started its modest activity in 2008, with a staff of 3 people. Today, the company has more than 300 employees. Our goal as an employer is to be a company that our staff can be proud of. We want to bring out the best skills of our colleagues and give them space and",
        "Opportunities for self-development. At Prime Concrete, we put a lot of time and effort into maintaining proper communication between engineers, technicians and executives. Part of this is Prime Academy - a platform through which seminars and trainings are held and where experience can be shared.",
        "The Executive and Strategic Committee focuses on the company's vision, mission and strategic goals and oversees business activities and operations, as well as risk management, internal controls and organizational development, which are carried out by the CEO and senior management of the company.",
    ],
    'team titles' => ["Governing Board", "Supervisory Board"],
    'team members' => ["Levan Lataria", ["Giorgi Akhvlediani", "Lasha Chipashvili", "Natia Janelidze"]],
    'team positions' => ["Executive Director", ["Deputy Executive Director", "Head of the construction department, partner", "independent member"]],
    'projects texts' => [
        "Client: Smart DevelopmentContractor: Prime ConcreteContract Type: Design and ConstructionValue: 1.5 million USD 'Foti Apartment'...",
        "Construction of reinforced concrete industrial roads and squares and municipal concrete paved roads is one of our...",
        "The Georgian construction company 'Prime Betoni' starts the project of the new 'Pace Terminal' in Poti, which is co-financed by the US...",
        "Lego blocks – a simple but diverse, effective and economical choice. The blocks fit together and…",
        "Client: APM Terminals PotiContractor: Prime Concrete Supervising company: Royal Haskoning DHV (Netherlands) Cost: USD 2.20 million Berth 15 was built…",
        "'Prime Beton' needs appropriate quality infrastructure and a comfortable learning environment to conduct a smooth training process..."
    ],
    'projects titles' => ["Poti apartment", "Berth-7", "Berth-15", "Container terminal", "Rehabilitation of the 7th berth, Poti", "Payment terminal"],
    'projects dates' => ["December 3, 2017", "September 13, 2015", "June 23, 2019", "September 4, 2022", "January 14, 2021", "August 3, 2017"],
    'news page' => [
        'titles' => ["Construction of water treatment plant", "pay Terminal project in Poti", "Construction of civil facilities"],
        'dot texts' => ["Date", "customer", "main contractor", "Supervising company"],
        'under dot texts' => [
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)"],
            ["December 22, 2021", "State Electricity System of Georgia", "Asian Development Bank", "Siemens Austria AG (Austria)"],
            ["January 9, 2020", "State Electricity System of Georgia", "Asian Development Bank", "Siemens Austria AG (Austria)"],
        ],
        'main texts' => [
            "&nbsp'Foti Apartment' is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp'Foti Apartment' includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbspWithin the framework of the 'Regional Network Development Project', JSC 'Georgian State Electric System' implemented the construction of a new substation 'Khorga-220/110'. The project was funded by the Asian Development Bank, the general contractor was Siemens Austria AG, and the construction works were carried out by 'Prime Betoni' company.<br><br>&nbspThe mentioned project will support the development of the Poti free industrial zone, will facilitate the safe extraction of power from the existing and future planned generation points, and will dramatically increase the reliability of the western energy hub.",
            "&nbsConstruction of reinforced concrete industrial roads and squares and municipal concrete paved roads is one of our directions. In this segment, we also carry out road infrastructure rehabilitation and construction, such as bridges, concrete barriers, drainage channels, gabions, retaining walls and others.<br><br>&nbspSince 2016, we have successfully completed more than 10 projects and built more than 60 km of roads. One of our main clients are 'Georgia Road Department' and 'Georgia Municipal Development Fund'",
        ]
    ],
    'contacts page' => [
        1 => 'contact information',
        2 => '595 00 86 65',
        3 => 'st. March 8 #55',
        4 => 'georgiandevelopment2023@gmail.com',
        5 => 'name, surname',
        6 => 'e-mail',
        7 => 'Write to us',
        8 => 'text...',
        9 => 'send',
        10 => 'Facebook',
        11 => 'Wait For Response',
    ],
    'project page' => [
        'titles' => ["berth-7", "berth-15", "container terminal", "Rehabilitation of 7th Berth", "Payment Terminal", "Poti Apartment"],
        'dot texts' => ["Date", "customer", "financing", "main contractor", "Supervising company", "subcontractor", "value"],
        'under dot texts' => [
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"],
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"],
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"],
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"],
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"],
            ["December 21, 2020", "United Water Supply Company of Georgia", "Asian Development Bank", "Ludwig Pfeiffer Hoch- und Tiefbau GmbH & co. KG (germany)", "Eptisa (Spain)", "Prime concrete", "1.72 million euros"]
        ],
        'main texts' => [
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
            "&nbsp“Foti Apartment” is the first project of prime concrete, where we performed both design and construction works. The project was handed over to the customer with complete external and internal repairs. Each apartment has been individually renovated and furnished, with a well-equipped yard and parking.<br><br>&nbsp“Foti Apartment” includes 22 individual apartments (50 - 132 m2) on 7 floors, a premium penthouse and commercial space on the first floor.",
        ],
        'next' => 'next project',
        'previous' => 'previous project',
    ],
    'sectors' => [
        'titles' => ["building materials", "civil and industrial projects", "marine works"],
        'building materials' => [
            'texts' => [
                1 => 'Production And Supply Of Quality Concrete Is Our Specialty. We Have Gained Considerable Experience In Concrete Production For The Specific Needs Of Industrial, Road And Port Projects. We Manufacture, Manufacture And Assemble Various Precast Concrete Structures.',
                2 => 'For The Production Of Concrete, We Use Inert Material Obtained From Our Quarries, Which Are Crushed, Calibrated And Washed According To Standards. The Use Of Different Types Of Cement, Chemicals, Metals And Synthetic Fibers Allows Us To Offer Our Clients Different Types Of Ready-Mixed Concrete According To The European Standard EN 206-1.',
                3 => 'We Have A Fully Equipped And Certified Laboratory For Testing Concrete And Inert Materials. Our Team Of Professional Experts Not Only Monitors Quality Every Day, But Also Works To Create Different Recipes For Specific Needs.',
            ],
        ],
        'civil and industrial projects' => [
            'texts' => [
                1 => 'Khobi, Samegrelo',
                2 => 'Construction of Kvemo Qvaloni Public School',
                3 => 'We pride ourselves on projects that directly improve the quality of life in our community. Over the years, we have created a significant portfolio of successful projects, including many buildings and structures such as:',
                4 => ["public schools and kindergartens;", "office and residential buildings;", "underground stations;", "high voltage electric substations;", "Large-scale warehouses and industrial factory buildings."],
                5 => ["Tbilisi", "Khobi, Samegrelo", "Khobi, Samegrelo"],
                6 => ["Construction of the extension of the 2nd line of the Tbilisi metro and the new university station", "Construction of substation in Khorga. Khorga 220/110 sq.m", "Construction of a fish processing plant in Kulevi"],
            ],
        ],
        'marine works' => [
            'texts' => [
                1 => 'The construction of marine-engineering facilities and port infrastructure is one of our main activities. Since 2012, we have been closely cooperating with the corporation "Poti Marine Port" (APM Terminals Poti) and PACE Terminals. Our activities include the following works:',
                2 => 'construction and reconstruction of the wharf;',
                3 => 'construction and reconstruction of underwater and water-side iron-concrete constructions;',
                4 => 'Construction of fiber-concrete cover of the container terminal;',
                5 => 'Installation works of iron-concrete beams;',
                6 => 'Installation of steel piles;',
                7 => 'electrical installation works, etc.',
                8 => 'Marine projects pose a particular security challenge. We have significant statistics of "failure-free" performance of the mentioned works. At the same time, we have successful experience in managing EPC and Design & Build multi-functional projects.',
            ],
        ],
    ],
    'search' => ['placeholder' => 'search', 'title' =>'start typing'],
    





];
